import cytoscape from 'cytoscape';
import Vue from 'vue'
Vue.use(cytoscape);

  
          var elems = {
    nodes: [
      { data: { id: 'DEVICE_1' } },
      { data: { id: 'DEVICE_2' } },
      { data: { id: 'DEVICE_3' } },
      { data: { id: 'DEVICE_4' } },
      { data: { id: 'DEVICE_5' } },
      { data: { id: 'DEVICE_6' } },
      { data: { id: 'DEVICE_7' } },
      { data: { id: 'DEVICE_8' } },
      { data: { id: 'DEVICE_9' } },
      { data: { id: 'DEVICE_10' } },
      { data: { id: 'DEVICE_11' } },
      { data: { id: 'DEVICE_12' } },
      { data: { id: 'DEVICE_13' } },
      { data: { id: 'DEVICE_14' } },
      { data: { id: 'DEVICE_15' } },
      { data: { id: 'DEVICE_16' } },
      { data: { id: 'DEVICE_17' } },
      { data: { id: 'DEVICE_18' } },
      { data: { id: 'DEVICE_19' } },
      { data: { id: 'DEVICE_20' } },
      { data: { id: 'DEVICE_21' } },
      { data: { id: 'DEVICE_22' } },
      { data: { id: 'DEVICE_23' } },
      { data: { id: 'DEVICE_24' } },
      { data: { id: 'DEVICE_25' } },
      { data: { id: 'DEVICE_26' } },
      { data: { id: 'DEVICE_27' } },
      { data: { id: 'DEVICE_28' } },
      { data: { id: 'DEVICE_29' } },
      { data: { id: 'DEVICE_30' } },
      { data: { id: 'DEVICE_31' } },
      { data: { id: 'DEVICE_32' } },
      { data: { id: 'DEVICE_33' } },
      { data: { id: 'DEVICE_34' } },
      { data: { id: 'DEVICE_35' } },
      { data: { id: 'DEVICE_36' } },
      { data: { id: 'DEVICE_37' } },
      { data: { id: 'DEVICE_38' } },
      { data: { id: 'DEVICE_39' } },
      { data: { id: 'DEVICE_40' } },
      { data: { id: 'DEVICE_41' } },
      { data: { id: 'DEVICE_42' } },
      { data: { id: 'DEVICE_43' } },
      { data: { id: 'DEVICE_44' } },
      { data: { id: 'DEVICE_45' } },
      { data: { id: 'DEVICE_46' } },
      { data: { id: 'DEVICE_48' } },
      { data: { id: 'DEVICE_47' } },
      { data: { id: 'DEVICE_49' } },
      { data: { id: 'DEVICE_50' } },
      { data: { id: 'DEVICE_51' } },
      { data: { id: 'DEVICE_52' } },
      { data: { id: 'DEVICE_53' } },
      { data: { id: 'DEVICE_54' } },
      { data: { id: 'DEVICE_55' } },
      { data: { id: 'DEVICE_56' } },
      { data: { id: 'DEVICE_57' } },
      { data: { id: 'DEVICE_58' } },
      { data: { id: 'DEVICE_59' } },
      { data: { id: 'DEVICE_60' } },
      { data: { id: 'DEVICE_61' } },
      { data: { id: 'DEVICE_62' } },
      { data: { id: 'DEVICE_65' } },
    ],
    edges: [
      { data: { source: 'DEVICE_45', target: 'DEVICE_1' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_2' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_3' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_4' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_5' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_6' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_7' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_8' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_9' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_10' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_11' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_12' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_13' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_14' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_15' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_16' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_17' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_18' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_19' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_20' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_21' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_22' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_23' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_24' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_25' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_26' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_27' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_28' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_29' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_30' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_31' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_32' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_33' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_34' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_35' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_36' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_37' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_38' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_39' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_40' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_41' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_42' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_43' } },
      { data: { source: 'DEVICE_45', target: 'DEVICE_44' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_1' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_3' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_4' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_5' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_6' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_7' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_8' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_9' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_10' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_11' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_12' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_13' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_14' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_15' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_16' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_17' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_18' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_19' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_20' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_21' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_22' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_23' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_24' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_25' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_26' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_27' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_28' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_29' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_30' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_31' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_32' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_33' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_34' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_35' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_36' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_37' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_38' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_39' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_40' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_41' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_42' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_43' } },
      { data: { source: 'DEVICE_2', target: 'DEVICE_44' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_2' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_3' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_4' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_5' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_6' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_7' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_8' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_9' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_10' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_11' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_12' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_13' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_14' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_15' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_16' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_17' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_18' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_19' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_20' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_21' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_22' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_23' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_24' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_25' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_26' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_27' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_28' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_29' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_30' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_31' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_32' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_33' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_34' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_35' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_36' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_37' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_38' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_39' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_40' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_41' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_42' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_43' } },
      { data: { source: 'DEVICE_1', target: 'DEVICE_44' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_1' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_2' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_3' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_4' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_5' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_6' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_7' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_8' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_9' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_10' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_11' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_12' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_13' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_14' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_15' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_16' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_17' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_18' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_19' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_20' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_21' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_22' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_23' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_24' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_25' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_26' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_27' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_28' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_29' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_30' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_31' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_32' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_33' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_34' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_35' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_36' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_37' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_38' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_39' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_40' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_41' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_42' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_43' } },
      { data: { source: 'DEVICE_46', target: 'DEVICE_44' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_47' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_49' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_50' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_51' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_52' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_53' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_54' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_55' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_56' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_57' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_58' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_59' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_60' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_61' } },
      { data: { source: 'DEVICE_48', target: 'DEVICE_62' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_47' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_49' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_50' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_51' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_52' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_53' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_54' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_55' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_56' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_57' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_58' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_59' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_60' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_61' } },
      { data: { source: 'DEVICE_63', target: 'DEVICE_62' } },
  
    ]
  };
  
  var cy = cytoscape({
    container: document.getElementById('cy'),
    autounselectify: true,
    style: [
      {"selector":"core","style":
        {"selection-box-color":"#AAD8FF","selection-box-border-color":"#8BB0D0","selection-box-opacity":"0.5"}
      },
      {"selector":"node","style":
        {"width":"118px","height":"100px","content":"data(id)","font-size":"24px","text-valign":"center","text-halign":"center","background-color":"#555","text-outline-color":"#555","text-outline-width":"2px","color":"#fff","overlay-padding":"6px","z-index":"10"}
      },
      {"selector":"node[?attr]","style":
        {"shape":"rectangle","background-color":"#aaa","text-outline-color":"#aaa","width":"16px","height":"16px","font-size":"6px","z-index":"1"}
      },
      {"selector":"node:selected","style":
        {"border-width":"6px","border-color":"#AAD8FF","border-opacity":"0.5","background-color":"#77828C","text-outline-color":"#77828C"}
      },
      {"selector":"edge","style":
        {"curve-style":"haystack","haystack-radius":"0","opacity":"0.4","line-color":"#bbb","width": "10px","overlay-padding":"3px"}
      }
    ],
    elements: elems,
    layout: {
          name: 'breadthfirst',
          directed: true,
          padding: 10
    }
  });
  
  var nodes = elems.nodes
  //recursively removing all children of the Start node (all nodes but the Start node will be removed)
  //递归地删除开始节点的所有子节点(所有节点但将删除开始节点)
  cy.$("#" + nodes[0].data.id).successors().targets().style("display", "none");
  
  //removes and restores nodes' children on click
  //在单击时删除和恢复节点的子节点
  cy.on('tap', 'node', function(){
    //if the node's children have been hidden
    //getting the element at 1 because the element at 0 is the node itself
    //want to check if its children are hidden
    //如果节点的子节点已经隐藏
    //得到1处的元素，因为0处的元素就是节点本身
    //想检查它的子对象是否隐藏
    if (this.connectedEdges().targets()[1].style("display") == "none"){
      //show the nodes and edges
      //显示节点和边
      this.connectedEdges().targets().style("display", "element");
    } else {
      //hide the children nodes and edges recursively
      //递归地隐藏子节点和边
      this.successors().targets().style("display", "none");
    }
  });
  