import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    logged: false,
    drawer: false,
    // localStor: [],
    localStor: JSON.parse(localStorage.getItem('posArr')) || [],
    
    // timelist:this.timelist,
    elems:{
      nodes: [
        {"SZ7FE01U10-OP1-N5K": {
          "ib_ip": "10.1.1.1",
          "ob_ip": "10.10.1.1",
          "area": "业务一区", 
          "role": "接入",
          "type": "Switch",
          "manu": "CISCO", 
          "model": "Nexus 5000", 
          "soft_ver": "n7700-sd-dfasd-1232.45093",
          "seq": "JG28585892",
          "manager": "贾玮玮",
        }},
        { data: { id: 'DEVICE_1' } },
        { data: { id: 'DEVICE_2' } },
        { data: { id: 'DEVICE_3' } },
        { data: { id: 'DEVICE_4' } },
        { data: { id: 'DEVICE_5' } },
        { data: { id: 'DEVICE_6' } },
        { data: { id: 'DEVICE_7' } },
        { data: { id: 'DEVICE_8' } },
        { data: { id: 'DEVICE_9' } },
        { data: { id: 'DEVICE_10' } },
        { data: { id: 'DEVICE_11' } },
        { data: { id: 'DEVICE_12' } },
        { data: { id: 'DEVICE_13' } },
        { data: { id: 'DEVICE_14' } },
        { data: { id: 'DEVICE_15' } },
        { data: { id: 'DEVICE_16' } },
        { data: { id: 'DEVICE_17' } },
        { data: { id: 'DEVICE_18' } },
        { data: { id: 'DEVICE_19' } },
        { data: { id: 'DEVICE_20' } },
        { data: { id: 'DEVICE_21' } },
        { data: { id: 'DEVICE_22' } },
        { data: { id: 'DEVICE_23' } },
        { data: { id: 'DEVICE_24' } },
        { data: { id: 'DEVICE_25' } },
        { data: { id: 'DEVICE_26' } },
        { data: { id: 'DEVICE_27' } },
        { data: { id: 'DEVICE_28' } },
        { data: { id: 'DEVICE_29' } },
        { data: { id: 'DEVICE_30' } },
        { data: { id: 'DEVICE_31' } },
        { data: { id: 'DEVICE_32' } },
        { data: { id: 'DEVICE_33' } },
        { data: { id: 'DEVICE_34' } },
        { data: { id: 'DEVICE_35' } },
        { data: { id: 'DEVICE_36' } },
        { data: { id: 'DEVICE_37' } },
        { data: { id: 'DEVICE_38' } },
        { data: { id: 'DEVICE_39' } },
        { data: { id: 'DEVICE_40' } },
        { data: { id: 'DEVICE_41' } },
        { data: { id: 'DEVICE_42' } },
        { data: { id: 'DEVICE_43' } },
        { data: { id: 'DEVICE_44' } },
        { data: { id: 'DEVICE_45' } },
        { data: { id: 'DEVICE_46' } },
        { data: { id: 'DEVICE_48' } },
        { data: { id: 'DEVICE_47' } },
        { data: { id: 'DEVICE_49' } },
        { data: { id: 'DEVICE_50' } },
        { data: { id: 'DEVICE_51' } },
        { data: { id: 'DEVICE_52' } },
        { data: { id: 'DEVICE_53' } },
        { data: { id: 'DEVICE_54' } },
        { data: { id: 'DEVICE_55' } },
        { data: { id: 'DEVICE_56' } },
        { data: { id: 'DEVICE_57' } },
        { data: { id: 'DEVICE_58' } },
        { data: { id: 'DEVICE_59' } },
        { data: { id: 'DEVICE_60' } },
        { data: { id: 'DEVICE_61' } },
        { data: { id: 'DEVICE_62' } },
        { data: { id: 'DEVICE_63' } },
      ],
      edges: [
        { data: { source: 'DEVICE_45', target: 'DEVICE_1' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_2' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_3' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_4' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_5' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_6' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_7' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_8' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_9' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_10' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_11' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_12' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_13' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_14' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_15' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_16' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_17' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_18' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_19' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_20' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_21' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_22' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_23' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_24' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_25' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_26' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_27' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_28' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_29' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_30' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_31' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_32' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_33' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_34' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_35' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_36' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_37' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_38' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_39' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_40' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_41' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_42' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_43' } },
        { data: { source: 'DEVICE_45', target: 'DEVICE_44' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_1' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_3' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_4' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_5' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_6' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_7' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_8' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_9' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_10' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_11' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_12' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_13' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_14' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_15' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_16' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_17' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_18' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_19' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_20' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_21' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_22' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_23' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_24' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_25' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_26' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_27' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_28' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_29' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_30' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_31' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_32' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_33' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_34' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_35' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_36' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_37' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_38' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_39' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_40' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_41' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_42' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_43' } },
        { data: { source: 'DEVICE_2', target: 'DEVICE_44' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_2' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_3' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_4' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_5' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_6' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_7' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_8' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_9' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_10' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_11' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_12' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_13' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_14' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_15' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_16' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_17' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_18' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_19' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_20' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_21' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_22' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_23' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_24' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_25' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_26' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_27' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_28' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_29' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_30' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_31' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_32' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_33' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_34' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_35' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_36' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_37' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_38' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_39' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_40' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_41' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_42' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_43' } },
        { data: { source: 'DEVICE_1', target: 'DEVICE_44' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_1' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_2' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_3' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_4' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_5' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_6' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_7' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_8' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_9' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_10' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_11' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_12' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_13' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_14' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_15' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_16' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_17' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_18' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_19' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_20' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_21' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_22' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_23' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_24' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_25' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_26' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_27' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_28' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_29' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_30' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_31' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_32' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_33' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_34' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_35' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_36' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_37' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_38' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_39' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_40' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_41' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_42' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_43' } },
        { data: { source: 'DEVICE_46', target: 'DEVICE_44' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_47' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_49' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_50' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_51' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_52' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_53' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_54' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_55' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_56' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_57' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_58' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_59' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_60' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_61' } },
        { data: { source: 'DEVICE_48', target: 'DEVICE_62' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_47' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_49' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_50' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_51' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_52' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_53' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_54' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_55' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_56' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_57' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_58' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_59' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_60' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_61' } },
        { data: { source: 'DEVICE_63', target: 'DEVICE_62' } },
    
      ]
    },
  },
  mutations: {
    SET_DRAWER: (state, drawer) => {
      state.drawer = drawer;
    },
    SET_LOGGED: (state, logged) => {
      state.logged = logged;
    },
    SET_LOCALSTOR: (state, rposition) => {
      state.localStor = rposition
      this.$store.dispatch('setPosition')
    }
  },
  actions: {
    setDrawer({ commit }, drawer) {
      commit('SET_DRAWER', drawer);
    },
    toggleDrawer(state) {
      state.drawer = ! state.drawer;
    },
    setPosition({ commit }, rposition) {
      var url = `http://127.0.0.1:3000/rdataroll`;
      this.$axios.get(url).then(result=>{
        // if(result.data.code == 1){
          var rposition = result.data.msg;
          commit('SET_LOCALSTOR', rposition)
        // }else{
        //   Toast("获取数据失败");
        // }
      })
    }
  },
  getters: {
    getDrawer: state => {
      return state.drawer
    },
    getLogger: state => {
      return state.logged
    },
  }
});
